AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'
  
  LogRetention:
    Type: Number
    Default: 14
  
  AlarmSNSTopicArn:
    Type: String
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
Resources:
  # internal queues DLQ
  NotificationCancellationActionInsertDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_workflow_cdc_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"
  
  # internal queues DLQ
  PaperEventsCostUpdateDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_workflow_papereventscostupdate_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"

  PaperEventsCostUpdateLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-paperEventsCostUpdateLambda-workflow"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:
  # Lambda functions
  NotificationCancellationActionInsertLambdaName:
    Value: !Sub "${ProjectName}-notificationCancellationActionInsert-workflow"
  
  # NotificationCancellationActionInsertLambdaAlarms DLQ
  NotificationCancellationActionInsertDLQName:
    Value: !GetAtt NotificationCancellationActionInsertDLQ.Outputs.QueueName
    Description: pn-delivery-push-notification-cancellationaction-insert_DLQ queue name
  NotificationCancellationActionInsertDLQURL:
    Value: !GetAtt NotificationCancellationActionInsertDLQ.Outputs.QueueURL
    Description: pn-delivery-push-notification-cancellationaction-insert_DLQ queue URL
  NotificationCancellationActionInsertDLQARN:
    Value: !GetAtt NotificationCancellationActionInsertDLQ.Outputs.QueueARN
    Description: pn-delivery-push-notification-cancellationaction-insert_DLQ queue ARN
  NotificationCancellationActionInsertDLQAlarmARN:
    Value: !GetAtt NotificationCancellationActionInsertDLQ.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push-notification-cancellationaction-insert_DLQ alarm ARN
  
  # Lambda functions
  PaperEventsCostUpdateLambdaName:
    Value: !Sub "${ProjectName}-paperEventsCostUpdate-workflow"
  
  PaperEventsCostUpdateDLQName:
    Value: !GetAtt PaperEventsCostUpdateDLQ.Outputs.QueueName
    Description: pn-delivery-push_paper_events_costo_update_DLQ queue name
  PaperEventsCostUpdateDLQURL:
    Value: !GetAtt PaperEventsCostUpdateDLQ.Outputs.QueueURL
    Description: pn-delivery-push_paper_events_costo_update_DLQ queue URL
  PaperEventsCostUpdateDLQARN:
    Value: !GetAtt PaperEventsCostUpdateDLQ.Outputs.QueueARN
    Description: pn-delivery-push_paper_events_costo_update_DLQ queue ARN
  PaperEventsCostUpdateDLQAlarmARN:
    Value: !GetAtt PaperEventsCostUpdateDLQ.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push_paper_events_costo_update_DLQ alarm ARN