logging.config=config/logback-local.xml
server.port=8081


# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD
spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

#Dynamodb configurations
pn.delivery-push-workflow.document-creation-request-dao.table-name=DocumentCreationRequest
pn.delivery-push-workflow.failed-notification-dao.table-name=PaperNotificationFailed

# Queue SQS configurations
pn.delivery-push-workflow.topics.from-external-channel=local-ext-channels-outputs
pn.delivery-push-workflow.topics.scheduled-actions=local-delivery-push-actions
pn.delivery-push-workflow.topics.new-notifications=local-delivery-push-inputs.fifo
pn.delivery-push-workflow.topics.nationalRegistriesEvents=local-national-registries-gateway
pn.delivery-push-workflow.topics.notification-rework-updater-event=delivery-push-to-notification-rework-updater

pn.delivery-push-workflow.external-channel-cx-id=pn-delivery-002
pn.delivery-push-workflow.safe-storage-cx-id=pn-delivery-push
pn.delivery-push-workflow.safe-storage-cx-id-updatemetadata=pn-delivery

spring.cloud.aws.sqs.enabled=true

pn.delivery-push-workflow.additional-langs-enabled=true
pn.delivery-push-workflow.webapp.direct-access-url-template-physical=http://localhost:8090/dist/direct_access_pf
pn.delivery-push-workflow.webapp.direct-access-url-template-legal=http://localhost:8090/dist/direct_access_pg
pn.delivery-push-workflow.webapp.quick-access-url-aar-detail-suffix=notifica?aar
pn.delivery-push-workflow.webapp.landing-url=https://www.dev.pn.pagopa.it
pn.delivery-push-workflow.webapp.faq-url-template-suffix=faq
pn.delivery-push-workflow.webapp.faqCompletionMomentHash=perfezionamento-quando
pn.delivery-push-workflow.webapp.faqSendHash=send-cosa-e

pn.delivery-push-workflow.delivery-base-url=http://localhost:8080
pn.delivery-push-workflow.data-vault-base-url=http://localhost:8084
pn.delivery-push-workflow.safe-storage-base-url=http://localhost:8120
pn.delivery-push-workflow.external-channel-base-url=http://localhost:8082
pn.delivery-push-workflow.user-attributes-base-url=http://localhost:8085
pn.delivery-push-workflow.external-registry-base-url=http://localhost:8087
pn.delivery-push-workflow.radd-alt-base-url=http://localhost:8099
pn.delivery-push-workflow.paper-channel-base-url=http://localhost:8088
pn.delivery-push-workflow.national-registries-base-url=http://localhost:1080
pn.delivery-push-workflow.templates-engine-base-url=http://localhost:8090
pn.delivery-push-workflow.emd-integration-base-url=http://localhost:8091
pn.delivery-push-workflow.action-manager-base-url=http://localhost:8092
pn.delivery-push-workflow.timeline-client-base-url=http://localhost:8093
pn.delivery-push-workflow.delivery-push-base-url=http://localhost:8094
pn.delivery-push-workflow.paper-tracker-base-url=http://localhost:8092

# raddExperimentationStoresName properties
pn.delivery-push-workflow.raddExperimentationStoresName[0]=radd-experimentation-zip-1
pn.delivery-push-workflow.raddExperimentationStoresName[1]=radd-experimentation-zip-2
pn.delivery-push-workflow.raddExperimentationStoresName[2]=radd-experimentation-zip-3
pn.delivery-push-workflow.raddExperimentationStoresName[3]=radd-experimentation-zip-4
pn.delivery-push-workflow.raddExperimentationStoresName[4]=radd-experimentation-zip-5

# Enables retry of the notification validation in case of SafeStorage 404 error
pn.delivery-push-workflow.safeStorageFileNotFoundRetry=false
pn.delivery-push-workflow.pago-pa-notification-base-cost=100
pn.delivery-push-workflow.pago-pa-notification-fee=100
pn.delivery-push-workflow.pago-pa-notification-vat=22

pn.delivery-push-workflow.pfnewworkflowstart=2099-02-13T23:00:00Z
pn.delivery-push-workflow.pfnewworkflowend=2099-03-31T23:00:00Z

# timeout di mancata risposta da external-channler
pn.delivery-push-workflow.external-channel.digital-send-noresponse-timeout=1m

# ritardo tra ritentativi nel caso di digitalcodes-retryable
pn.delivery-push-workflow.external-channel.digital-retry-delay=1m


#Timing workflow NEW
pn.delivery-push-workflow.time-params.waiting-for-read-courtesy-message=5s
pn.delivery-push-workflow.time-params.second-notification-workflow-waiting-time=7s
pn.delivery-push-workflow.time-params.scheduling-days-success-digital-refinement=7s
pn.delivery-push-workflow.time-params.scheduling-days-failure-digital-refinement=15s
pn.delivery-push-workflow.time-params.scheduling-days-success-analog-refinement=10s
pn.delivery-push-workflow.time-params.scheduling-days-failure-analog-refinement=10s
pn.delivery-push-workflow.time-params.notification-non-visibility-time=21:00
pn.delivery-push-workflow.time-params.time-to-add-in-non-visibility-time-case=20s
# Defines how long before the attachment retention expires need to start "check attachment retention"
pn.delivery-push-workflow.time-params.check-attachment-time-before-expiration=10d
# Time to add when attachment retention is expiring
pn.delivery-push-workflow.time-params.attachment-time-to-add-after-expiration=120d

# Config giorni retention degli allegati dopo la data di presa visione o decorrenza termini
pn.delivery-push-workflow.retention-attachment-days-after-refinement=120

# Start date for feature recipient unreachable refinement after ten days from AAR
pn.delivery-push-workflow.feature-unreachable-refinement-postAARStartDate=2024-11-27T00:00:00Z

pn.delivery-push-workflow.activation-deceased-workflow-date=2024-11-27T00:00:00Z

pn.delivery-push-workflow.error-correction-level-qr-code=h

#Configuration for send notification attachment, AAR, and AAR type. Comma separated list made up by:
# "Configuration start time" (UTC);"Send attachment mode for analog";"Send attachment mode for simple registered letter";"AAR template type"
pn.delivery-push-workflow.paper-send-mode=1970-01-01T00:00:00Z;AAR-DOCUMENTS-PAYMENTS;AAR-DOCUMENTS-PAYMENTS;AAR_NOTIFICATION,2023-11-30T23:00:00Z;AAR;AAR;AAR_NOTIFICATION_RADD
#Configuration for send notification attachment, AAR, and AAR type. Comma separated list made up by:
# "Configuration start time" (UTC);"Send attachment mode for analog";"Send attachment mode for simple registered letter";"Send attachment mode for legal mail";"AAR template type" - if <RADD_TEMPLATE_DEFINITION> is last parameter value ("AAR template type") it means that the AAR template type need to be obtained dynamically, used for RADD experimentation
pn.delivery-push-workflow.pn-send-mode=1970-01-01T00:00:00Z;AAR-DOCUMENTS-PAYMENTS;AAR;AAR;AAR_NOTIFICATION,2024-05-22T22:00:00Z;AAR-DOCUMENTS-PAYMENTS;AAR;AAR-DOCUMENTS-PAYMENTS;AAR_NOTIFICATION,2024-05-22T22:00:00Z;AAR-DOCUMENTS-PAYMENTS;AAR;AAR-DOCUMENTS-PAYMENTS;<RADD_TEMPLATE_DEFINITION>,2024-06-26T22:00:00Z;AAR-DOCUMENTS-PAYMENTS;AAR;AAR-DOCUMENTS-PAYMENTS;AAR_NOTIFICATION_RADD_ALT
pn.delivery-push-workflow.timeline-client-enabled-start-date=2025-06-13T15:13:00Z
#Feature flag per attivazione invio solo AAR per PEC con copertura RADD e PF
pn.delivery-push-workflow.aarOnlyPecForRaddAndPf=${PN_DELIVERY_PUSH_AARONLYPECFORRADDANDPF:false}
pn.delivery-push-workflow.templateURLforPEC=${PN_DELIVERY_PUSH_TEMPLATEURLFORPEC:/templates-engine-private/v1/templates/notification-aar-for-pec}
#Feature flag per attivazione flusso di spedizione analogica con timeout
pn.delivery-push-workflow.start-analog-workflow-timeout-feature-date=2025-07-15T00:00:00Z
#Feature flag per attivazione flusso di gestione messaggi di cortesia in fase di choose delivery
pn.delivery-push-workflow.send-courtesy-at-choose-delivery-activation-date=2028-07-15T00:00:00Z
#Determines the coverage verification granularity: 'Light' (ZIP code only) or 'Complete' (ZIP code and Location) or 'OLD'.
pn.delivery-push-workflow.radd-search-mode=${PN_DELIVERYPUSHWORKFLOW_RADDSEARCHMODE:OLD}

pn.delivery-push-workflow.rework-ttl-address-range=10
pn.delivery-push-workflow.notification-rework-document-expiring-range=30
pn.delivery-push-workflow.invalidable-categories=PREPARE_ANALOG_DOMICILE,PREPARE_ANALOG_DOMICILE_FAILURE,SEND_ANALOG_DOMICILE,SEND_ANALOG_PROGRESS,SEND_ANALOG_FEEDBACK,ANALOG_SUCCESS_WORKFLOW,ANALOG_FAILURE_WORKFLOW,SCHEDULE_REFINEMENT,REFINEMENT,COMPLETELY_UNREACHABLE_CREATION_REQUEST,COMPLETELY_UNREACHABLE,ANALOG_WORKFLOW_RECIPIENT_DECEASED
