logging.config=config/logback-local.xml

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD
spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

# Queue SQS configurations
pn.delivery-push-workflow.topics.from-external-channel=local-ext-channels-outputs
pn.delivery-push-workflow.topics.scheduled-actions=local-delivery-push-actions
pn.delivery-push-workflow.topics.new-notifications=local-delivery-push-inputs.fifo
pn.delivery-push-workflow.topics.nationalRegistriesEvents=local-national-registries-gateway

spring.cloud.aws.sqs.enabled=true


