package it.pagopa.pn.deliverypushworkflow.exceptions;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;
import lombok.Getter;

public class PnDeliveryPushExceptionCodes extends PnExceptionsCodes {

    // raccolgo qui tutti i codici di errore di delivery push
    public static final String ERROR_CODE_DELIVERYPUSH_NOTFOUND = "PN_DELIVERYPUSH_NOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_UPLOADFILEERROR = "PN_DELIVERYPUSH_UPLOADFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_UPDATEMETAFILEERROR = "PN_DELIVERYPUSH_UPDATEMETAFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_ERRORCOMPUTECHECKSUM = "PN_DELIVERYPUSH_ERRORCOMPUTECHECKSUM";
    public static final String ERROR_CODE_DELIVERYPUSH_ATTACHMENTCHANGESTATUSFAILED = "PN_DELIVERYPUSH_ATTACHMENTCHANGESTATUSFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALIDEVENTCODE = "PN_DELIVERYPUSH_INVALIDEVENTCODE";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALIDATTEMPT = "PN_DELIVERYPUSH_INVALIDATTEMPT";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALIDADDRESSSOURCE = "PN_DELIVERYPUSH_INVALIDADDRESSSOURCE";
    public static final String ERROR_CODE_DELIVERYPUSH_SENDDIGITALTIMELINEEVENTNOTFOUND = "PN_DELIVERYPUSH_SENDDIGITALTIMELINEEVENTNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_SCHEDULEDDIGITALTIMELINEEVENTNOTFOUND = "PN_DELIVERYPUSH_SCHEDULEDDIGITALTIMELINEEVENTNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_SCHEDULEDPREPARETIMELINEEVENTNOTFOUND = "PN_DELIVERYPUSH_SCHEDULEDPREPARETIMELINEEVENTNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_LASTADDRESSATTEMPTNOTFOUND = "PN_DELIVERYPUSH_LASTADDRESSATTEMPTNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_TIMELINEEVENTNOTFOUND = "PN_DELIVERYPUSH_TIMELINEEVENTNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_ERRORCOURTESY = "PN_DELIVERYPUSH_ERRORCOURTESY";
    public static final String ERROR_CODE_DELIVERYPUSH_ERRORCOURTESYIO = "PN_DELIVERYPUSH_ERRORCOURTESYIO";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALIDRECEIVEDPAPERSTATUS = "PN_DELIVERYPUSH_INVALIDRECEIVEDPAPERSTATUS";
    public static final String ERROR_CODE_DELIVERYPUSH_STATUSNOTFOUND = "PN_DELIVERYPUSH_STATUSNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_FEEDBACKNOTFOUND = "PN_DELIVERYPUSH_FEEDBACKNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_TIMELINENOTFOUND = "PN_DELIVERYPUSH_TIMELINENOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_ROOTIDNOTFOUND = "PN_DELIVERYPUSH_ROOTIDNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_CONTACTPHASENOTFOUND = "PN_DELIVERYPUSH_CONTACTPHASENOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_DELIVERYNOTFOUND = "PN_DELIVERYPUSH_DELIVERYNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_SAVELEGALFACTSFAILED = "PN_DELIVERYPUSH_SAVELEGALFACTSFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_ADDTIMELINEFAILED = "PN_DELIVERYPUSH_ADDTIMELINEFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_CHANNELTYPENOTSUPPORTED = "PN_DELIVERYPUSH_CHANNELTYPENOTSUPPORTED";
    public static final String ERROR_CODE_DELIVERYPUSH_SENDPECNOTIFICATIONFAILED = "PN_DELIVERYPUSH_SENDPECNOTIFICATIONFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_SENDSMSNOTIFICATIONFAILED = "PN_DELIVERYPUSH_SENDSMSNOTIFICATIONFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_SENDEMAILNOTIFICATIONFAILED = "PN_DELIVERYPUSH_SENDEMAILNOTIFICATIONFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_ADDRESSTYPENOTSUPPORTED = "PN_DELIVERYPUSH_ADDRESSTYPENOTSUPPORTED";
    public static final String ERROR_CODE_DELIVERYPUSH_HANDLEEVENTFAILED = "PN_DELIVERYPUSH_HANDLEEVENTFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_ACTIONTYPENOTSUPPORTED = "PN_DELIVERYPUSH_ACTIONTYPENOTSUPPORTED";
    public static final String ERROR_CODE_DELIVERYPUSH_TIMELINEELEMENTFAILED = "PN_DELIVERYPUSH_TIMELINEELEMENTFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_GENERATEPDFFAILED = "PN_DELIVERYPUSH_GENERATEPDFFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_UPDATEFAILED = "PN_DELIVERYPUSH_UPDATEFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_NO_RECIPIENT_IN_NOTIFICATION = "PN_DELIVERYPUSH_NORECIPIENTINNOTIFICATION";
    public static final String ERROR_CODE_DELIVERYPUSH_PAPERUPDATEFAILED = "PN_DELIVERYPUSH_PAPERUPDATEFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_NOTIFICATIONFAILED = "PN_DELIVERYPUSH_NOTIFICATIONFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_DUPLICATED_ITEMD = "PN_DELIVERYPUSH_DUPLICATED_ITEM";
    public static final String ERROR_CODE_DELIVERYPUSH_END_WORKFLOW_STATUS_NOT_HANDLED = "PN_DELIVERYPUSH_END_WORKFLOW_STATUS_NOT_HANDLED";
    public static final String ERROR_CODE_DELIVERYPUSH_PAPERCHANNELSENDCOSTCHANGED = "PN_DELIVERYPUSH_PAPERCHANNELSENDCOSTCHANGED";
    public static final String ERROR_CODE_DELIVERYPUSH_PAYMENT_UPDATE_RETRY_EXCEPTION = "ERROR_CODE_DELIVERYPUSH_PAYMENTUPDATERETRYEXCEPTION";
    public static final String ERROR_CODE_DELIVERYPUSH_CONFIGURATION_NOT_FOUND = "ERROR_CODE_DELIVERYPUSH_CONFIGURATIONNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_TIMELINE_ELEMENT_NOT_PRESENT = "ERROR_CODE_DELIVERYPUSH_TIMELINEELEMENTNOTPRESENT";
    public static final String ERROR_CODE_DELIVERYPUSH_TOTAL_COST_NOT_PRESENT = "ERROR_CODE_DELIVERYPUSH_TOTALCOSTNOTPRESENT";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_INVALID_SUPPORTED_EVENT = "PN_DELIVERYPUSH_ROUTER_INVALID_SUPPORTED_EVENT";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_MULTIPLE_HANDLERS_FOUND = "PN_DELIVERYPUSH_ROUTER_MULTIPLE_HANDLERS_FOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_DESERIALIZATION = "PN_DELIVERYPUSH_ROUTER_DESERIALIZATION";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_EVENT_TYPE_MISSING = "PN_DELIVERYPUSH_ROUTER_EVENT_TYPE_MISSING";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_HANDLER_NOT_FOUND = "PN_DELIVERYPUSH_ROUTER_NOT_FOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALID_TEMPLATE = "PN_DELIVERYPUSH_INVALID_TEMPLATE";
    public static final String ERROR_CODE_DELIVERY_PUSH_NOTIFICATION_NOT_ACCEPTED = "PN_DELIVERY_PUSH_NOTIFICATION_NOT_ACCEPTED";
    public static final String ERROR_CODE_DELIVERYPUSH_FUTURE_ACTION_NOTFOUND= "PN_ACTIONMANAGER_ERROR_CODE_FUTURE_ACTION_NOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_ACTION_CONFLICT = "PN_ACTIONMANAGER_ERROR_CODE_ACTION_CONFLICT";

}
