package it.pagopa.pn.deliverypushworkflow.middleware.queue.consumer.resumepostpayment;

public enum ResumeValidationReason {
    VALID,
    RECIPIENT_NOT_FOUND,
    NOTIFICATION_IUN_MISMATCH,
    PAYMENT_NOT_FOUND,
    NOTIFICATION_CANCELLED,
    NOTIFICATION_VIEWED,
    NOTIFICATION_REWORKED,
    PREPARE_ALREADY_PRESENT,
    SCHEDULE_ANALOG_WORKFLOW_NOT_FOUND,
    SCHEDULE_ANALOG_WORKFLOW_TOO_RECENT,
    FIRST_ANALOG_SEND_NOT_FOUND,
    SECOND_ATTEMPT_TRIGGER_NOT_FOUND,
    DIGITAL_FAILURE_WORKFLOW_NOT_FOUND,
    SCHEDULE_REFINEMENT_NOT_FOUND,
    PHYSICAL_ADDRESS_NOT_FOUND
}